---
title: "test"
author: "Naomi Buell and Richie Rivera"
format: html
editor: visual
---

## Intro

```{r}
#| label: load packages

pacman::p_load(tidyverse, janitor, httr, jsonlite, skimr, RSocrata)
```

Load [PLACES: Local Data for Better Health, County Data 2024 release](https://data.cdc.gov/500-Cities-Places/PLACES-Local-Data-for-Better-Health-County-Data-20/swc5-untb/about_data) for New York state by census tract. 

```{r}
#| load: CDC places API

df <- read.socrata(
    "https://data.cdc.gov/resource/swc5-untb.json",
    app_token = "Oor3v3DJAEoCdk17eeRa8uhFK",
    # API key secret = "njb5uguoy84h93qx2gwgy36264wgrbqfyey5ldkauti3ks5ay",
    email = "naomi.buell13@spsmail.cuny.edu",
    password = "H@FT5%yuKwX7fw!R"
)

# API endpoint from link above
base_url <- "https://data.cdc.gov/resource/swc5-untb.json?measure=Feeling socially isolated among adults"


# Define the query parameters
query_params <- list()

# Make a GET request to the API endpoint with query parameters
response <- GET(base_url, query = query_params)

# Check if the request was successful
if (status_code(response) == 200) {
    # Parse the JSON response
    data <- fromJSON(content(response, "text"))
} else {
    cat(
        "Failed to retrieve data. HTTP Status code:",
        status_code(response),
        "\n"
    )
}
```

Browse the data.

```{r}
#| label: data exploration

clean_data <- data |> clean_names()

clean_data |> skim()
clean_data <- clean_data |>
    select(
        stateabbr,
        statedesc,
        countyname,
        countyfips,
        tractfips,
        totalpopulation,
        totalpop18plus,
        geolocation,
        isolation_crudeprev,
        isolation_crude95ci
    )

```